// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Asset struct {
	ID string `json:"id"`
}

type Config struct {
	Scope           []interface{} `json:"scope,omitempty"`
	Ports           []*int        `json:"ports,omitempty"`
	Blacklist       []*string     `json:"blacklist,omitempty"`
	Domains         []*string     `json:"domains,omitempty"`
	Resolvers       []*string     `json:"resolvers,omitempty"`
	Ips             []*string     `json:"ips,omitempty"`
	Cirds           []interface{} `json:"cirds,omitempty"`
	Transformations []interface{} `json:"transformations,omitempty"`
	Database        []interface{} `json:"database,omitempty"`
	BruteForce      *bool         `json:"bruteForce,omitempty"`
	Alterations     *bool         `json:"alterations,omitempty"`
}

type CreateAssetInput struct {
	SessionToken string      `json:"sessionToken"`
	AssetName    *string     `json:"assetName,omitempty"`
	Data         interface{} `json:"data,omitempty"`
}

type CreateSessionInput struct {
	Config interface{} `json:"config"`
}

type CreateSessionJSONInput struct {
	Config string `json:"config"`
}

type Session struct {
	SessionToken string `json:"sessionToken"`
}

type SessionStats struct {
	WorkItemsInProcess   *int `json:"workItemsInProcess,omitempty"`
	WorkItemsWaiting     *int `json:"workItemsWaiting,omitempty"`
	WorkItemsProcessable *int `json:"workItemsProcessable,omitempty"`
}

type SystemStats struct {
	TotalWorkItemsReceived    *int `json:"totalWorkItemsReceived,omitempty"`
	TotalWorkItemsDone        *int `json:"totalWorkItemsDone,omitempty"`
	TotalWorkItemsCancelled   *int `json:"totalWorkItemsCancelled,omitempty"`
	TotalWorkItemsProcess     *int `json:"totalWorkItemsProcess,omitempty"`
	TotalWorkItemsError       *int `json:"totalWorkItemsError,omitempty"`
	TotalWorkItemsWaiting     *int `json:"totalWorkItemsWaiting,omitempty"`
	TotalWorkItemsProcessable *int `json:"totalWorkItemsProcessable,omitempty"`
	TotalWorkItemsSystem      *int `json:"totalWorkItemsSystem,omitempty"`
}
