// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateEventInput struct {
	SessionID string  `json:"session_id"`
	EventName string  `json:"event_name"`
	Data      *string `json:"data,omitempty"`
	Type      string  `json:"type"`
}

type CreateSessionInput struct {
	Config string `json:"config"`
}

type Event struct {
	ID string `json:"id"`
}

type Session struct {
	Token string `json:"token"`
}
