package server

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/owasp-amass/config/config"
	"github.com/owasp-amass/engine/api/graphql/server/model"
	"github.com/owasp-amass/engine/sessions"
	"github.com/owasp-amass/engine/types"
	oam "github.com/owasp-amass/open-asset-model"
	"github.com/owasp-amass/open-asset-model/domain"
	"github.com/owasp-amass/open-asset-model/network"
)

// CreateSession is the resolver for the createSession field.
func (r *mutationResolver) CreateSession(ctx context.Context, input model.CreateSessionInput) (*model.Session, error) {
	testSession := &model.Session{
		SessionToken: "00000000-0000-0000-0000-0000000000033", //?
	}
	return testSession, nil
}

// CreateSessionFromJSON is the resolver for the createSessionFromJson field.
func (r *mutationResolver) CreateSessionFromJSON(ctx context.Context, input model.CreateSessionJSONInput) (*model.Session, error) {
	var config config.Config

	if err := json.Unmarshal([]byte(input.Config), &config); err != nil {
		fmt.Println(err)
	}
	// Populate FROM/TO in transformations
	for k, t := range config.Transformations {
		t.Split(k)
	}

	session, err := sessions.NewSession(&config)
	if err != nil {
		return nil, err
	}

	token, err := r.Mgr.Add(session)
	if err != nil {
		return nil, err
	}

	return &model.Session{SessionToken: token.String()}, nil
}

// CreateAsset is the resolver for the createAsset field.
func (r *mutationResolver) CreateAsset(ctx context.Context, input model.CreateAssetInput) (*model.Asset, error) {
	token, _ := uuid.Parse(input.SessionToken)

	session := r.Mgr.Get(token)
	if session == nil {
		return nil, errors.New("invalid session")
	}

	data, err := json.Marshal(input.Data)
	if err != nil {
		return nil, err
	}
	// Unmarshal json into AssetData struct
	var assetData types.AssetData
	if err := json.Unmarshal(data, &assetData); err != nil {
		return nil, err
	}

	ad := fixAssetData(&assetData)
	if ad == nil {
		return nil, errors.New("failed to build the AssetData")
	}

	// Create and schedule new event
	event := &types.Event{
		UUID:      uuid.New(),
		Name:      *input.AssetName,
		SessionID: token,
		Data:      ad,
		Type:      types.EventTypeAsset,
	}

	if err := r.Sched.Schedule(event); err != nil {
		return nil, errors.New("failed to create asset")
	}
	// TEST: Broadcast asset creation message to client subscribers
	session.PubSub.Publish("Log created asset")
	return &model.Asset{ID: event.UUID.String()}, nil
}

// TerminateSession is the resolver for the terminateSession field.
func (r *mutationResolver) TerminateSession(ctx context.Context, sessionToken string) (*bool, error) {
	result := false
	token, _ := uuid.Parse(sessionToken)

	if r.Mgr.Get(token) != nil {
		r.Mgr.Cancel(token)
		result = true
	} else {
		return &result, errors.New("invalid session token")
	}
	return &result, nil
}

// SessionStats is the resolver for the sessionStats field.
func (r *queryResolver) SessionStats(ctx context.Context, sessionToken string) (*model.SessionStats, error) {
	token, _ := uuid.Parse(sessionToken)

	if r.Mgr.Get(token) == nil {
		return nil, errors.New("invalid session token")
	}

	ssResp := r.Sched.GetSessionStats(token, types.EventTypeAsset)
	return &model.SessionStats{
		WorkItemsInProcess:   &ssResp.SessionWorkItemsInProcess,
		WorkItemsWaiting:     &ssResp.SessionWorkItemsWaiting,
		WorkItemsProcessable: &ssResp.SessionWorkItemsProcessable,
	}, nil
}

// SystemStats is the resolver for the systemStats field.
func (r *queryResolver) SystemStats(ctx context.Context, sessionToken string) (*model.SystemStats, error) {
	panic(fmt.Errorf("not implemented: SystemStats - systemStats"))
}

// LogMessages is the resolver for the logMessages field.
func (r *subscriptionResolver) LogMessages(ctx context.Context, sessionToken string) (<-chan *string, error) {
	token, _ := uuid.Parse(sessionToken)
	session := r.Mgr.Get(token)

	fmt.Println("LogMessages callled")
	if session != nil {
		session.PubSub.Publish("Channel created")
		ch := session.PubSub.Subscribe()
		return ch, nil
	}
	return nil, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

func fixAssetData(ad *types.AssetData) *types.AssetData {
	switch v := ad.OAMAsset.(type) {
	case domain.FQDN:
		return &types.AssetData{
			OAMAsset: &v,
			OAMType:  oam.FQDN,
		}
	case network.IPAddress:
		return &types.AssetData{
			OAMAsset: &v,
			OAMType:  oam.IPAddress,
		}
	case network.Netblock:
		return &types.AssetData{
			OAMAsset: &v,
			OAMType:  oam.Netblock,
		}
	case network.AutonomousSystem:
		return &types.AssetData{
			OAMAsset: &v,
			OAMType:  oam.ASN,
		}
	case network.RIROrganization:
		return &types.AssetData{
			OAMAsset: &v,
			OAMType:  oam.RIROrg,
		}
	}
	return nil
}
